# 1. NOME DA APLICACAO
spring.application.name=financeiro

# 2. CONEXAO COM O MYSQL LOCAL (UBUNTU)
# Note que trocamos as variáveis ${} pelos valores fixos do seu PC
spring.datasource.url=jdbc:mysql://localhost:3306/financeiro
spring.datasource.username=root
spring.datasource.password=11092004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. CONFIGURACAO DE E-MAIL
# Se não for usar e-mail agora, pode deixar como está, mas o app vai dar erro se tentar enviar sem a senha real
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=claudinhon152@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 5. PORTA DO SERVIDOR
server.port=8080