# 1. NOME DA APLICACAO
spring.application.name=financeiro

# 2. CONEXAO COM O MYSQL
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=EoNJyCjRtQhLjRKAZBRCgVRaOBOGqEGe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 4. CONFIGURACAO DE E-MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=claudinhon152@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 5. PORTA DO SERVIDOR
server.port=8080