# Banco local
spring.datasource.url=jdbc:mysql://localhost:3306/financeiro
spring.datasource.username=root
spring.datasource.password=11092004

# JWT
jwt.secret=WYdN+KJlEH2IWyNEQZMlVYxDlONOzdvtYlYjeAFT03P7sAUU0cPFBWnOK95mYdHt
jwt.expiration=86400000

# E-mail (preencha com suas credenciais quando for testar recuperação de senha)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Desenvolvimento
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false